### PR TITLE
Add tkinter and kconfiglib for PX4-Autopilot#17100

### PR DESCRIPTION
**Pull request by PetervdPerk-NXP**
Add Tkinter and kconfiglib to cybwin/python toolchain to get boardguiconfig working on Windows for
https://github.com/PX4/PX4-Autopilot/pull/17100

### CODE REVIEW

**Comment by MaEtUgR** [comment]
@PetervdPerk-NXP Thanks for adding, I'd need to build a new installer then. Last time it was blocked because the MSI file size is limited and the Cygwin base gained weight 😬

**Comment by PetervdPerk-NXP** [comment]
@dagar does PX4 still require Python 2? @MaEtUgR  Otherwise you might want to drop that from PX4-windows-toolchain to save space.

**Comment by MaEtUgR** [comment]
@PetervdPerk-NXP It doesn't. I just kept it for backwards compatibility such that people can build releases. I would have dropped it if it'd save the right order of magnitude of space. Let me check again maybe they shrank Cygwin again even if it's unlikely.

**Comment by hamishwillee** [comment]
@MaEtUgR FWIW I like the fact that I can build older releases with the latest toolchain. But when we get to the point that the current stable and last release are both on Python 3 we should revisit this (if not earlier)

**Pull request merged**
